### ISSUE TITLE
Resources not ready during deployment

### ISSUE THREAD

**Issue by IainD925** [Azure-Samples/ai-studio-in-a-box#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>azd up

### Any log messages given by the failure
>Deployment Error Details:
AccountProvisioningStateInvalid: Call to Microsoft.CognitiveServices/accounts failed. Error message: Account /subscriptions/abcd-123a-4fac-91a2-677d3e1ad96b/resourceGroups/rg-ai-inabox/providers/Microsoft.CognitiveServices/accounts/cog-ai-inabox-r6b in state Accepted

Private Endpoints then object to being updated:

```
ValidationError: Managed network cannot be disabled once enabled.
BadRequest: When updating a shared private link resource, only 'requestMessage' property is allowed to be modified
```

### Expected/desired behavior
> 
If you redeploy issue does not remain.  Looks like a longer wait period required during creation.

### OS and Version?
> Windows 10.

### Versions
>https://github.com/Azure-Samples/ai-studio-in-a-box/commit/f6754c3b85a83b5bdae504b8227a099a4c80b532

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MarcoABCardoso** [comment]
Hello @IainD925!

This is a known issue with deploying Shared Private Links and AI Projects with Managed vNets and through Bicep.
Please refer to the [FAQ](https://github.com/Azure-Samples/ai-studio-in-a-box?tab=readme-ov-file#faq) for a workaround:

> BadRequest: When updating a shared private link resource, only 'requestMessage' property is allowed to be modified
  After the first time you deploy shared private links, subsequent deployments will fail with this message. Run the command below to disable the re-deployment of shared private links.
  `azd env set AZURE_DEPLOY_SHARED_PRIVATE_LINKS false`

> ValidationError: Managed network cannot be disabled once enabled.
  Same as above for AI Projects. Run the command below to disable the re-deployment of the AI Project.
  `azd env set AZURE_DEPLOY_AI_PROJECT false`

It seems this happens because these resources are deployed into a "Provisioning" state and soon flip to an "Active" state. The new deployment (incorrectly) tries to update this state and fails.

I'm looking into whether there's a way to skip the workaround above, if not, we'll track this as an issue with the resources `Microsoft.MachineLearningServices/workspaces` and `Microsoft.Search searchServices/sharedPrivateLinkResources`

**Comment by IainD925** [comment]
Hi @MarcoABCardoso I applied both 
```
azd env set AZURE_DEPLOY_SHARED_PRIVATE_LINKS false
azd env set AZURE_DEPLOY_AI_PROJECT false
```

```
then re-ran azd up, process still failed on a private endpoint although the log is sparse:
 (x) Failed: Private Endpoint: pl-cog-hub-ai-in-a-box-qag
  |     ==| Creating/Updating resources
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InternalServerError: An error occurred.
```
One final question, how do we set the option to use identity rather than key?  When I use azd up after the first run it doesn't ask.

**Comment by IainD925** [comment]
I'm going to roll my own.
